### ISSUE TITLE
QUE PORRA É ESSA CARALHO????????????????????????

### ISSUE THREAD

**Issue by DioBruh** [Mahitozin/Simple-Calculator#1]
ESSE CARA É MALUCO VSFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by DioBruh** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by nebulotico** [comment]
Mais um dia normal
